### PR TITLE
Main/screen

### PR DESCRIPTION
**Pull request by Chiragmodi01**
- Main home screen
- google search
- change background preferences in settings

image
image

### CODE REVIEW

**Review by harshitpaliwal95 — APPROVED** [review]
code looks good
- remove commented code / add preview

**Review by aurobindoGupta — APPROVED** [review]
nice work.

**Comment by harshitpaliwal95** [comment]
suggestion google search input should be more visible

**Comment by Chiragmodi01** [comment]
> suggestion google search input should be more visible

will brighten the color

**Pull request merged**
