### PR TITLE
Quotes and weather

### PR DESCRIPTION
**Pull request by Chiragmodi01**
- Random quote on page reload
- Weather details display
- Pre weather data, Loader

did some style fixes and updates index file with polishes

### CODE REVIEW

**Review by Asuraking1n — APPROVED** [review]
UI Looks, awesome man,
Code is extracted and god

**Comment by agrawalshanu708** [comment]
UI looks good
code structure is good
you can merge it

**Review by agrawalshanu708 — APPROVED** [review]
UI looks good
code structure is well managed
you can merge

**Comment by aurobindoGupta** [comment]
- nice UI.\
- clean code.
- nice work

**Pull request merged**
